id = "silverscript"
name = "SilverScript"
version = "0.1.0"
schema_version = 1
description = "SilverScript language support."

languages = ["languages/silverscript"]

[grammars.silverscript]
# useful for development
# repository = "file:///D:/Dev/kaspa/silverscript"

# @TODO(izio): change before merge
repository = "https://github.com/IzioDev/silverscript-new"
rev = "591d7a9263c3fe579fc89eaeba77e557be08f0d2"
path = "tree-sitter"

[language_servers.silverscript-lsp]
command = "silverscript-lsp"
